// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCybdn1jKVsV5OJN--iwEu6lxtM7VXCKD0',
    appId: '1:92648324189:android:3b23eec942eb6174bd61b4',
    messagingSenderId: '92648324189',
    projectId: 'flutter-cert-11f7d',
    databaseURL: 'https://flutter-cert-11f7d-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-cert-11f7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUE3KqRxDN8ggPlQNYpQqhbuqqhiL2hO8',
    appId: '1:92648324189:ios:99ee7a9c8b04e34dbd61b4',
    messagingSenderId: '92648324189',
    projectId: 'flutter-cert-11f7d',
    databaseURL: 'https://flutter-cert-11f7d-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-cert-11f7d.firebasestorage.app',
    iosBundleId: 'com.example.flutterCertFinal',
  );
}
